### ISSUE TITLE
`neuro job save` fails with unspecified error

### ISSUE THREAD

**Issue by astaff** [neuromation/platform-client-python#1037] opened 2019-09-06 00:48 UTC
#### Description:

When issuing `neuro job save` I am getting an error `ERROR: Expecting value: line 1 column 1 (char 0)`

#### Example:

```
neuro job save setup image:neuro/custom
WARNING: job-9a566125-3771-47f1-a464-102e1947442dFound 9 jobs matching name=setup, owner=astaff: , job-bf72a4ef-99ec-4272-ab0e-89b152798608Found 9 jobs matching name=setup, owner=astaff: , job-a0b75506-7f0f-426d-9016-ff4f74448922Found 9 jobs matching name=setup, owner=astaff: , job-d6a85c05-1260-497c-a6b6-81d82b10adb8Found 9 jobs matching name=setup, owner=astaff: , job-d23f8fd9-d008-4b09-a277-282b10a467a6Found 9 jobs matching name=setup, owner=astaff: , job-6011eb18-e0b4-44c1-bb87-85e7a3cf346eFound 9 jobs matching name=setup, owner=astaff: , job-23ded443-f40b-42b2-a13b-c66a1b07ebd3Found 9 jobs matching name=setup, owner=astaff: , job-e186dfb7-4b52-430c-88d5-20b5aa330fd5Found 9 jobs matching name=setup, owner=astaff: , job-cb580b22-51ef-43ce-9009-5a851d08810d
Saving job-cb580b22-51ef-43ce-9009-5a851d08810d -> image://astaff/neuro/custom:latest
ERROR: Expecting value: line 1 column 1 (char 0)
```

Please note that this command is also being used by `make setup` which is a part of a project template.

**Comment by ayushkovskiy** [comment] 2019-09-06 07:23
The server (`platform-monitoring`) send non-json response, but the client (legitimately) expects json chunks according to the protocol.

Perhaps, the problem is connected to our recent networking problems we experience at least on `dev` cluster:
```
            if 400 <= resp.status:
                err_text = await resp.text()
                err_cls = self._exception_map.get(resp.status, IllegalArgumentError)
>               raise err_cls(err_text)
E               neuromation.api.core.IllegalArgumentError: 
E               <html><head>
E               <meta http-equiv="content-type" content="text/html;charset=utf-8">
E               <title>502 Server Error</title>
E               </head>
E               <body text=#000000 bgcolor=#ffffff>
E               <h1>Error: Server Error</h1>
E               <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
E               <h2></h2>
E               </body></html>
```

**Comment by ayushkovskiy** [comment] 2019-09-06 07:27
side note: @astaff please kill your jobs (`job-cb580b22-51ef-43ce-9009-5a851d08810d` is still running).

We are aware of the issue that `neuro setup` can leave a job running, will be fixed asap.

**Comment by ayushkovskiy** [comment] 2019-09-06 07:36
No, it is not: the empty chunk `b''` came from the server

**Comment by ayushkovskiy** [comment] 2019-09-06 07:55
on `dev` everything's OK

**Comment by ayushkovskiy** [comment] 2019-09-06 07:56
Perhaps, the version `platform-monitoring` on `staging` is outdated? Though I don't remember if we modified `neuro save` on server lately

**Comment by ayushkovskiy** [comment] 2019-09-06 07:57
there were changes touching permission check, but they are unrelated since the user has permissions on the job.

**Comment by ayushkovskiy** [comment] 2019-09-06 08:06
@asvetlov client's `await resp.content.readline()` constantly reads empty bytes `b''` :confused:

**Comment by ayushkovskiy** [comment] 2019-09-06 08:08
I know!! on staging, the version of `platform-monitoring` is very old, without support of streaming neuro-save! The deploy must help.

**Comment by ayushkovskiy** [comment] 2019-09-06 09:01
thanks @zubenkoivan for deploying platform-monitoring on staging, everything's working now.

**Closed by ayushkovskiy** 2019-09-06 09:01 UTC
Labels: CLIents, platform
